### ISSUE TITLE
VLC requirement no error

### ISSUE THREAD

**Issue by haenry** [vidify/vidify#64]
Nice tool!
If no VLC is installed and vidify is installed via pip, then the app won't start on windows 10. There's not even an error message suggesting the install.
Typing _vidify_ in cmd simply does nothing.

After installing VLC everything works fine.

**Comment by marioortizmanero** [comment]
Yes, the issue is that by default, the debug mode is disabled (enabled with `--debug`). This means that any errors are hidden to the user. It's done because VLC for instance has a ton of unnecessary messages in the command line, and they make it impossible to read the lyrics. This will be solved for sure once I make some kind of widget inside the GUI to show the lyrics, but for now I don't know how it could be solved...

**Comment by haenry** [comment]
What about `vlc_args = "--quiet"` in the class VLCPlayer? You already seem to use this flag in the normal mode. Then there shouldn't be any VLC messages actually.
When I run --debug and use this flag, I only see messages from your program. So I think you just need to put an approriate error message and set the logging level accordingly for the normal mode (Error or warning)

btw this is the error I am getting without VLC
```Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\Scripts\vidify-script.py", line 11, in <module>
    load_entry_point('vidify==2.1.0', 'console_scripts', 'vidify')()
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vidify\__main__.py", line 56, in main
    start_gui(config)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vidify\__main__.py", line 33, in start_gui
    window = MainWindow(config)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vidify\gui\window.py", line 61, in __init__
    self.player = initialize_player(config.player, config)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vidify\player\__init__.py", line 53, in initialize_player
    mod = importlib.import_module(player.module)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vidify\player\vlc.py", line 14, in <module>
    import vlc
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vlc.py", line 207, in <module>
    dll, plugin_path  = find_lib()
  File "c:\users\user1\appdata\local\programs\python\python37\lib\site-packages\vlc.py", line 167, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\users\user1\appdata\local\programs\python\python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] module not found```

**Comment by marioortizmanero** [comment]
You're right. Stderr is no longer blocked. I've opened this issue on audiosync to enable/disable debug messages dynamically: https://github.com/vidify/audiosync/issues/51
