### ISSUE TITLE
Vidify with mpv doesn't exit

### ISSUE THREAD

**Issue by marioortizmanero** [vidify/vidify#89]
When I close VIdify when using Mpv, it's stuck in there and I can't close it.

**Comment by marioortizmanero** [comment]
This wasn't actually fixed, in the latest release:

```
Traceback (most recent call last):
  File "vidify/gui/window.py", line 165, in on_setup_done
    self.player = initialize_player(player, self.config)
  File "vidify/player/__init__.py", line 77, in initialize_player
    obj = cls(*params)
  File "vidify/player/mpv.py", line 52, in __init__
    self._mpv.register_key_binding("CLOSE_WIN", quit)
NameError: name 'quit' is not defined
zsh: abort (core dumped)  ./dev/vidify/vidify
```

See https://github.com/jaseg/python-mpv/issues/48
